### PR TITLE
Removed useless/deprecated code

### PR DESCRIPTION
**Pull request by lpaulsen93**

### CODE REVIEW

**Comment by selfthinker** [comment]
I suspect this makes the plugin incompatible with older DokuWiki versions?

**Comment by Klap-in** [comment]
Autoloading is included in DokuWiki already for years

**Comment by Klap-in** [comment]
But plugin.info.txt needs an update, maybe that some recent fixes does not yet arrive the users now.

**Comment by selfthinker** [comment]
> Autoloading is included in DokuWiki already for years

Thanks, that's good to know.

**Pull request merged**
